- name: 'default'
  uriPattern: '{@package}/{@controller}(/{@action})'
  defaults:
    '@action': 'index'
    '@format': 'html'
  appendExceedingArguments: true

- name: 'Project Lemon Mainpage'
  uriPattern: ''
  defaults:
    '@package': 'Lemon.Project'
    '@controller': 'Standard'
    '@action': 'index'

- name: 'TicTacToe'
  uriPattern: 'tictactoe/{@action}'
  defaults:
    '@package': 'Lemon.Project'
    '@controller': 'ticTacToe'
  appendExceedingArguments: true


- name: 'Notes main page'
  uriPattern: 'note/{@action}'
  defaults:
    '@package': 'Lemon.Project'
    '@controller': 'Note'
  appendExceedingArguments: true

- name: 'Tic POST'
  uriPattern: 'tictactoe/updateField/{@ticTacToe}'
  httpMethods: [ 'POST' ]
  defaults:
    '@package': 'Lemon.Project'
    '@controller': 'ticTacToe'
    '@action': 'updateField'
