- name: 'Wisteria Mainpage'
  uriPattern: ''
  defaults:
    '@package': 'Wisteria.Wisteria'
    '@controller': 'Standard'
    '@action': 'index'

#####################
# Fallback route
#####################

-
  name: 'default'
  uriPattern: '{@controller}(/{@action})'
  defaults:
    '@action':     'index'
    '@package': 'Wisteria.Wisteria'
    '@format':     'html'
  appendExceedingArguments: true

